image: rvancea/maven-chrome-jdk8:latest

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test

# Store artifacts
  artifacts:
    when: always
    name: "Extent_Reports"
    paths:
    - Reports/*
    expire_in: 1 h
