image: rvancea/maven-chrome-jdk8:latest

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test

# Store artifacts
  artifacts:
    when: always
    name: "report"
    paths:
    - C:/Users/priran/eclipse-workspace/Advance_10DLC_Admin_Portal_Automation_Framework/Reports/*
    expire_in: 1 h